### ISSUE TITLE
No such module 'Parse'

### ISSUE THREAD

**Issue by Rizora** [back4app/ios-swift-quickstart-example#1]
Build error in swift:9:8: No such module 'Parse'

As there is no documentation on this at all I am very frustrated

**Comment by mpc20001** [comment]
I think this is a routing error. Let me take a look and get back to you.

**Comment by mpc20001** [comment]
I pushed a fix to the main branch but just in case you want to fix it yourself - open my Target > Build Settings > Search Paths > Framework Search Paths. Add two values: $(PROJECT_DIR) and $(inherited) to the search paths. That should stop the error. Here is a link that explains it better - https://stackoverflow.com/questions/30663180/no-such-module-parse
