### ISSUE TITLE
Quickstart does not register users for push notifications

### ISSUE THREAD

**Issue by Rizora** [back4app/ios-swift-quickstart-example#2]
I have enabled push notifications and added App & Client ID but when tested I do not get a pop up and notifications are not sent or enabled on the iPhone.

**Comment by mpc20001** [comment]
This version does not actually register for push notifications. The installation object that is created is just to prove that the parse sdk has been setup properly.

**Comment by mpc20001** [comment]
Im working on a version that will include the push notification code and will release it soon.

**Comment by mpc20001** [comment]
Rizora if you want to contact me directly for help with push email me at iosdev22@gmail.com
